BASE_PROJECTS_FOLDER_NAME = 'projects'
TRAINING_FILES_FOLDER_NAME = 'trainingfiles'
NETWORK_FILES_FOLDER_NAME = 'networkfiles'
PROJECT_DATASETS_FOLDER_NAME = 'datasets'
TEST_FILES_FOLDER_NAME = 'test'
WTF_CSRF_ENABLED = True
SECRET_KEY = 'gHS^2,m[sHQM31Uys&f$nH2L,a91!'